package main

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/fzf-labs/protoc-gen-go-errors/v2/errors"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

const (
	errorsPackage  = protogen.GoImportPath("github.com/go-kratos/kratos/v2/errors")
	fmtPackage     = protogen.GoImportPath("fmt")
	runtimePackage = protogen.GoImportPath("runtime")
	strconvPackage = protogen.GoImportPath("strconv")
)

var enCases = cases.Title(language.AmericanEnglish, cases.NoLower)

// generateFile generates a _errors.pb.go file containing kratos errors definitions.
func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Enums) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_errors.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-errors. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.QualifiedGoIdent(fmtPackage.Ident(""))
	g.QualifiedGoIdent(runtimePackage.Ident(""))
	g.QualifiedGoIdent(strconvPackage.Ident(""))
	generateFileContent(gen, file, g)
	return g
}

// generateFileContent generates the kratos errors definitions, excluding the package statement.
func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	if len(file.Enums) == 0 {
		return
	}

	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the kratos package it is being compiled against.")
	g.P("const _ = ", errorsPackage.Ident("SupportPackageIsVersion1"))
	g.P()
	g.P("type ErrorReasonErrors struct {\n\tcode    int\n\treason  string\n\tmessage string\n\ti18n    map[string]string\n\terr     error\n\targs    []interface{}\n\tlang    string\n\tline    string\n}\n\nfunc (e *ErrorReasonErrors) Error() *errors.Error {\n\tmetadata := map[string]string{}\n\tif e.err != nil {\n\t\tmetadata[\"cause\"] = e.err.Error()\n\t}\n\tif e.line != \"\" {\t\n\t\tmetadata[\"line\"] = e.line\n\t}\n\tmessage := e.message\n\tif e.lang != \"\" {\n\t\tif _, ok := e.i18n[e.lang]; ok {\n\t\t\tmessage = e.i18n[e.lang]\n\t\t}\n\t}\n\tif len(e.args) > 0 {\n\t\tmessage = fmt.Sprintf(message, e.args...)\n\t}\n\treturn errors.New(e.code, e.reason, message).WithMetadata(metadata)\n}\n\ntype Option func(gen *ErrorReasonErrors)\n\nfunc WithError(err error) Option {\n\treturn func(e *ErrorReasonErrors) {\n\t\te.err = err\n\t}\n}\n\nfunc WithFmtMsg(args ...interface{}) Option {\n\treturn func(e *ErrorReasonErrors) {\n\t\te.args = args\n\t}\n}\n\nfunc WithLine() Option {\n\tvar fileLine string\n\t_, file, line, ok := runtime.Caller(2)\n\tif ok {\n\t\tfileLine = file + \":\" + strconv.Itoa(line)\n\t}\n\treturn func(e *ErrorReasonErrors) {\n\t\te.line = fileLine\n\t}\n}\n\nfunc WithI18N(lang string) Option {\n\treturn func(e *ErrorReasonErrors) {\n\t\te.lang = lang\n\t}\n}")
	g.P()
	index := 0
	for _, enum := range file.Enums {
		if !genErrorsReason(gen, file, g, enum) {
			index++
		}
	}
	// If all enums do not contain 'errors.code', the current file is skipped
	if index == 0 {
		g.Skip()
	}
}

func genErrorsReason(_ *protogen.Plugin, _ *protogen.File, g *protogen.GeneratedFile, enum *protogen.Enum) bool {
	code := 0
	message := ""
	i18n := &errors.I18N{}
	defaultCode := proto.GetExtension(enum.Desc.Options(), errors.E_DefaultCode)
	if ok := defaultCode.(int32); ok != 0 {
		code = int(ok)
	}
	if code > 600 || code < 0 {
		panic(fmt.Sprintf("Enum '%s' range must be greater than 0 and less than or equal to 600", string(enum.Desc.Name())))
	}
	defaultMessage := proto.GetExtension(enum.Desc.Options(), errors.E_DefaultMessage)
	if ok := defaultMessage.(string); ok != "" {
		message = ok
	}
	defaultI18n := proto.GetExtension(enum.Desc.Options(), errors.E_DefaultI18N)
	if ok := defaultI18n.(*errors.I18N); ok != nil {
		i18n = ok
	}

	var ew errorWrapper
	for _, v := range enum.Values {
		enumCode := code
		enumMessage := message
		enumI18n := i18n
		eCode := proto.GetExtension(v.Desc.Options(), errors.E_Code)
		if ok := eCode.(int32); ok != 0 {
			enumCode = int(ok)
		}
		// If the current enumeration does not contain 'errors.code'
		// or the code value exceeds the range, the current enum will be skipped
		if enumCode > 600 || enumCode < 0 {
			panic(fmt.Sprintf("Enum '%s' range must be greater than 0 and less than or equal to 600", string(v.Desc.Name())))
		}
		if enumCode == 0 {
			continue
		}
		eMessage := proto.GetExtension(v.Desc.Options(), errors.E_Message)
		if ok := eMessage.(string); ok != "" {
			enumMessage = ok
		}

		eI18n := proto.GetExtension(v.Desc.Options(), errors.E_I18N)
		if ok := eI18n.(*errors.I18N); ok != nil {
			enumI18n = ok
		}

		comment := v.Comments.Leading.String()
		if comment == "" {
			comment = v.Comments.Trailing.String()
		}

		err := &errorInfo{
			Name:       string(enum.Desc.Name()),
			Value:      string(v.Desc.Name()),
			HTTPCode:   enumCode,
			Message:    enumMessage,
			CamelValue: case2Camel(string(v.Desc.Name())),
			Comment:    comment,
			HasComment: len(comment) > 0,
			I18N:       enumI18n,
		}
		ew.Errors = append(ew.Errors, err)
	}
	if len(ew.Errors) == 0 {
		return true
	}
	g.P(ew.execute())

	return false
}

func case2Camel(name string) string {
	if !strings.Contains(name, "_") {
		if name == strings.ToUpper(name) {
			name = strings.ToLower(name)
		}
		return enCases.String(name)
	}
	strs := strings.Split(name, "_")
	words := make([]string, 0, len(strs))
	for _, w := range strs {
		hasLower := false
		for _, r := range w {
			if unicode.IsLower(r) {
				hasLower = true
				break
			}
		}
		if !hasLower {
			w = strings.ToLower(w)
		}
		w = enCases.String(w)
		words = append(words, w)
	}

	return strings.Join(words, "")
}
